//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ExampleGameMod.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "16.8.1.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute(@"<?xml version=""1.0"" encoding=""utf-16""?>
<ArrayOfString xmlns:xsi=""http://www.w3.org/2001/XMLSchema-instance"" xmlns:xsd=""http://www.w3.org/2001/XMLSchema"">
  <string>github:///CitiesSkylinesMods/TMPE</string>
  <string>steam://url/CommunityFilePage/2389228470</string>
</ArrayOfString>")]
        public global::System.Collections.Specialized.StringCollection requires {
            get {
                return ((global::System.Collections.Specialized.StringCollection)(this["requires"]));
            }
            set {
                this["requires"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute(@"<?xml version=""1.0"" encoding=""utf-16""?>
<ArrayOfString xmlns:xsi=""http://www.w3.org/2001/XMLSchema-instance"" xmlns:xsd=""http://www.w3.org/2001/XMLSchema"">
  <string>github:///drok/SupplyChainColoring</string>
  <string>steam://url/CommunityFilePage/2325122732</string>
</ArrayOfString>")]
        public global::System.Collections.Specialized.StringCollection recommends {
            get {
                return ((global::System.Collections.Specialized.StringCollection)(this["recommends"]));
            }
            set {
                this["recommends"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute(@"<?xml version=""1.0"" encoding=""utf-16""?>
<ArrayOfString xmlns:xsi=""http://www.w3.org/2001/XMLSchema-instance"" xmlns:xsd=""http://www.w3.org/2001/XMLSchema"">
  <string>steam://url/CommunityFilePage/433249875</string>
  <string>github:///arislancrescent/CS-EnhancedHearseAI</string>
  <string>app:///EnhancedHearseAI.Identity</string>
</ArrayOfString>")]
        public global::System.Collections.Specialized.StringCollection conflicts {
            get {
                return ((global::System.Collections.Specialized.StringCollection)(this["conflicts"]));
            }
            set {
                this["conflicts"] = value;
            }
        }
    }
}
